name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        ref: master

    - name: Set up Java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Docker image for building
      run: docker build -f DockerfileForBuild -t plantuml-service-builder .

    - name: Run build
      run: docker run --rm -v $(pwd):/app -e GRADLE_USER_HOME=/app/.gradle plantuml-service-builder ./gradlew stage

    - name: Check build artifacts
      run: |
        if [ ! -f "./bin/plantuml-service.jar" ]; then
          echo "Build failed: JAR file not found"
          exit 1
        fi
        echo "Build successful: JAR file created"

    - name: Get version from build.gradle
      id: get_version
      run: |
        VERSION=$(grep "^version " build.gradle | cut -d "'" -f 2)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Release version: $VERSION"

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew release

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ghcr.io/bitjourney/plantuml-service:${{ steps.get_version.outputs.version }}
        build-args: |
          PLANTUML_SERVICE_VERSION=${{ steps.get_version.outputs.version }}
